import streamlit as st
import numpy as np
import spacy
import joblib

import en_core_web_md

# Set up browser page configurations
st.set_page_config(
    page_title="Email/SMS Spam Classifier",
    page_icon="✉️",
    layout="centered"
)

# Cache heavy assets so they load exactly ONCE when the web server boots up
@st.cache_resource
def load_production_assets():
    """Loads the SpaCy language backbone and pre-trained classification models."""
    # Load SpaCy medium model for 300-dimensional semantic word vectors
    #nlp = spacy.load("en_core_web_md")
    nlp = en_core_web_md.load()
    
    # Load the trained model and label encoder generated by train.py
    model = joblib.load('spam_classifier_model.pkl')
    le = joblib.load('label_encoder.pkl')
    
    return nlp, model, le

# UI Styling and Layout
st.title("✉️ Smart Message Classifier")
st.markdown("""
This production application leverages **300-dimensional SpaCy semantic word vectors** 
and a **Scikit-Learn LinearSVC** model to detect spam text messages. 
""")
st.write("---")

# Safe asset initialization checkpoint
try:
    nlp, model, le = load_production_assets()
    assets_ready = True
except Exception as e:
    st.error(f"⚠️ **Deployment Error:** Unable to load model assets. Details: {e}")
    st.info("💡 **Fix:** Please ensure you have run `train.py` first and that `spam_classifier_model.pkl` and `label_encoder.pkl` exist in this directory.")
    assets_ready = False

# Text Input Area
user_input = st.text_area(
    "Analyze a Message:", 
    placeholder="Type or paste your text message / email string here...", 
    height=150
)

# Evaluation and Inference Logic
if st.button("Classify Text", type="primary") and assets_ready:
    if not user_input.strip():
        st.warning("⚠️ Please provide a text string before requesting classification.")
    else:
        with st.spinner("Analyzing linguistic features and structural vectors..."):
            # 1. Capture semantic context utilizing the SpaCy embedding structure
            vector = nlp(user_input).vector.astype(np.float32)
            
            # 2. Structure 1D array (300,) into a structured 2D array (1, 300) for scikit-learn
            vector_2d = vector.reshape(1, -1)
            
            # 3. Request classification outcome from the trained framework
            numeric_pred = model.predict(vector_2d)[0]
            
            # 4. Map index integer back to the user-friendly target string ('spam' or 'ham')
            decoded_label = le.inverse_transform([numeric_pred])[0]
        
        # Display polished classification metrics
        st.subheader("Classification Summary")
        
        if decoded_label.lower() == "spam":
            st.error(f"🚨 **Alert:** This text block matches typical **{decoded_label.upper()}** patterns.")
            st.markdown("""
            **Indicators detected:** 
            * High frequency of sales/promotional semantic anchors
            * Urgency patterns matching typical phishing or marketing scripts
            """)
        else:
            st.success(f"✅ **Safe:** This text block is classified as **{decoded_label.upper()}** (Legitimate).")
            st.markdown("**Indicators detected:** Conversational phrasing, standard vocabulary density, and authentic syntax structures.")

# Footer layout documentation
st.write("---")
st.markdown("<small style='color: gray;'>Engineering Highlight: Engineered with optimized feature vector matrix scaling and multi-threaded inference batch models.</small>", unsafe_allow_html=True)
